### ISSUE TITLE
Bot que Lê e Grava Informações em uma Google Sheets

### ISSUE THREAD

**Issue by RPengo** [DesenvolvimentoDeBots/DesenvolvimentoDeBots#29]
var token = "Insira o Token do seu Bot";
var telegramUrl = "https://api.telegram.org/bot" + token;
var webAppUrl = "Adicione o Link criado após implantar seu projeto";

function inArray(target, array) {
  for(var a = 0; a < array.length; a++)  {
    if(array[a] == target) {
      return true; }
     }
      return false; 
     }

function getMe() {
  var url = telegramUrl + "/getMe";
  var response = UrlFetchApp.fetch(url);}

function doGet(e) {
  return HtmlService.createHtmlOutput("Olá");}

function setWebhook() {
  var url = telegramUrl + "/setWebhook?url=" + webAppUrl;
  var response = UrlFetchApp.fetch(url);
  
}

function sendText(chatId, text, keyBoard) {
  var data = {
    method: "post",
    payload: {
      method: "sendMessage",
      chat_id: String(chatId),
      text: text,
      parse_mode: "HTML",
      reply_markup: JSON.stringify(keyBoard)
    }
  };
  UrlFetchApp.fetch('https://api.telegram.org/bot' + token + '/', data);
}

function sendTexto(chatIdf,textf) {
  var urlf = telegramUrl + "/sendMessage?chat_id=" + chatIdf + "&text=" + textf;
  var response = UrlFetchApp.fetch(urlf);}

function doPost(e) {
//parse user data
var contents = JSON.parse(e.postData.contents);
//set spreadsheet 
var ssId = "Adicione o link da sua planilha google sheets";
var expenseSheetre =  SpreadsheetApp.openById(ssId).getSheetByName("Realizadas");
var expenseSheetta =  SpreadsheetApp.openById(ssId).getSheetByName("Tarefas");
  
  
  var keyBoard = {
        "inline_keyboard": [
          [{"text": "Segunda", 'callback_data': 'segunda'},
           {"text": "Terça", 'callback_data': 'terca'}],

          [{"text": "Quarta", 'callback_data': 'quarta'},
           {"text": "Quinta", 'callback_data': 'quinta'}],

          [{"text": "Sexta", 'callback_data': 'sexta'},
           {"text": "Sábado", 'callback_data': 'sabado'}]
          ]

  };
  
  
  if (contents.callback_query) {
    var id_callback = contents.callback_query.message.chat.id;
     var data = contents.callback_query.data;
 
 
    switch(data) {
        case 'segunda':      var segunda = expenseSheetta.getRange("A1:A30").getValues();
                              for (var b = 0; b < segunda.length; b++){       
                              sendTexto(id_callback ,segunda[b])}; break;

        case 'terca':
                              var terca = expenseSheetta.getRange("B1:B30").getValues();
                              for (var c = 0; c < terca.length; c++){       
                              sendTexto(id_callback,terca[c])}; break;
                              
        case 'quarta':
                              var quarta = expenseSheetta.getRange("C1:C30").getValues();
                              for (var d = 0; d < quarta.length; d++){       
                              sendTexto(id_callback,quarta[d])}; break;
                              
        case 'quinta':
                              var quinta = expenseSheetta.getRange("D1:D30").getValues();
                              for (var e = 0; e < quinta.length; e++){       
                              sendTexto(id_callback,quinta[e])}; break;
                              
        case 'sexta':
                              var sexta = expenseSheetta.getRange("E1:E30").getValues();
                              for (var f = 0; f < sexta.length; f++){       
                              sendTexto(id_callback,sexta[f])}; break;
                              
        case 'sabado':
                              var sabado = expenseSheetta.getRange("F1:F30").getValues();
                              for (var g = 0; g < sabado.length; g++){       
                              sendTexto(id_callback,sabado[g])}; break;
  }
  }
  
    if (contents.message) {
    var id_message = contents.message.chat.id; 
    var text = contents.message.text; 
    var item = text.split("=");
    var firstName = contents.message.from.first_name;
    
      if (text.indexOf("=") !== -1 ) { 
    //get date
     var nowDate = new Date(); 
     var date = nowDate; 
   expenseSheetre.appendRow([date, item[0], item[1], firstName]);
    sendText(id_message,"Tarefa Registrada!"); 
  }

    switch(text) {
        case '/segunda':      var segundab = expenseSheetta.getRange("A1:A30").getValues();
                              for (var h = 0; h < segundab.length; h++){       
                              sendTexto(id_message,segundab[h])}; break;
            
        case '/terca':
                              var tercab = expenseSheetta.getRange("B1:B30").getValues();
                              for (var i = 0; i < tercab.length; i++){       
                              sendTexto(id_message,tercab[i])}; break;
                              
        case '/quarta':
                              var quartab = expenseSheetta.getRange("C1:C30").getValues();
                              for (var j = 0; j < quartab.length; j++){       
                              sendTexto(id_message,quartab[j])}; break;
                              
        case '/quinta':
                              var quintab = expenseSheetta.getRange("D1:D30").getValues();
                              for (var k = 0; k < quintab.length; k++){       
                              sendTexto(id_message,quintab[k])}; break;
                              
        case '/sexta':
                              var sextab = expenseSheetta.getRange("E1:E30").getValues();
                              for (var l = 0; l < sextab.length; l++){       
                              sendTexto(id_message,sextab[l])}; break;
                              
        case '/sabado':
                              var sabadob = expenseSheetta.getRange("F1:F30").getValues();
                              for (var m = 0; m < sabadob.length; m++){       
                              sendTexto(id_message,sabadob[m])}; break;
                              
        case '/segunda@atividadesfrv_bot':      
                              var segundac = expenseSheetta.getRange("A1:A30").getValues();
                              for (var n = 0; n < segundac.length; n++){       
                              sendTexto(id_message,segundac[n])}; break;
            
        case '/terca@atividadesfrv_bot':
                              var tercac = expenseSheetta.getRange("B1:B30").getValues();
                              for (var o = 0; o < tercac.length; o++){       
                              sendTexto(id_message,tercac[o])}; break;
                              
        case '/quarta@atividadesfrv_bot':
                              var quartac = expenseSheetta.getRange("C1:C30").getValues();
                              for (var p = 0; p < quartac.length; p++){       
                              sendTexto(id_message,quartac[p])}; break;
                              
        case '/quinta@atividadesfrv_bot':
                              var quintac = expenseSheetta.getRange("D1:D30").getValues();
                              for (var q = 0; q < quintac.length; q++){       
                              sendTexto(id_message,quintac[q])}; break;
                              
        case '/sexta@atividadesfrv_bot':
                              var sextac = expenseSheetta.getRange("E1:E30").getValues();
                              for (var r = 0; r < sextac.length; r++){       
                              sendTexto(id_message,sextac[r])}; break;
                              
        case '/sabado@atividadesfrv_bot':
                              var sabadoc = expenseSheetta.getRange("F1:F30").getValues();
                              for (var s = 0; s < sabadoc.length; s++){       
                              sendTexto(id_message,sabadoc[s])}; break;
                              
        case '/menu@atividadesfrv_bot':
                              sendText(id_message, "Olá " + firstName +  ", selecione um dia da semana:",keyBoard); break;
                              
        case '/menu':
                              sendText(id_message, "Olá " + firstName +  ", selecione um dia da semana:",keyBoard); break;

   } 
}
}

**Comment by Andredego** [comment]
Repeita o pv 
Repeita os membro 
Proibido pornografia 
Proibido chama membro no pv sem ser convidado
Proibido fala palavrão xingar membro etc...

**Comment by Andredego** [comment]
@vitormattos como passou desenvolvimento do bot com mais eficaz ?

**Comment by vitormattos** [comment]
Nem sabia da existência deste bot aqui.

**Comment by Andredego** [comment]
Estou aprendendo a mexe...
Senhor pode me ensinar?

Em ter, 7 de set de 2021 08:32, Vitor Mattos ***@***.***>
escreveu:

**Comment by vitormattos** [comment]
Não conheço este bot.

**Comment by Andredego** [comment]
Vlw

**Comment by Andredego** [comment]
Como eu posso criar e configurar um bot

Em ter, 7 de set de 2021 08:40, Vitor Mattos ***@***.***>
escreveu:

**Comment by vitormattos** [comment]
Neste repositório tem várias informações úteis no estudo para criação de bots:

https://github.com/DesenvolvimentoDeBots/DesenvolvimentoDeBots

**Comment by vitormattos** [comment]
Questionamentos sanados
